### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by v4nz666** [v4nz666/7drl2017#20]
Get some swashbucklin music rockin:

- Sailing theme [sailing.wav]
- City theme (or one for each of 4 sizes of cities) [city.wav] or [city1.wav, city2.wav, city3.wav, city4.wav]
- Battle theme [battle.wav]

**Comment by Break-the-silence** [comment]
Sweet! Ima get onthis after work yo

**Comment by Break-the-silence** [comment]
K, so Song types will be:
City Mode
Sailing Mode
Battle Mode

**Comment by Break-the-silence** [comment]
are there any others?

**Comment by v4nz666** [comment]
That should do

**Comment by v4nz666** [comment]
As nice to haves, though, the individual shops could have their own theme, see #9 for the list.

**Comment by Break-the-silence** [comment]
https://drive.google.com/drive/folders/0B4-Tbksse5FlZlprbHFmUTBmSG8
