### ISSUE TITLE
Shops

### ISSUE THREAD

**Issue by v4nz666** [v4nz666/7drl2017#9]
Dock(exit city)
General Store (buy provisions)
Tavern (Hire crew, Buy drinks)
Consolate (Get contracts)
Shipyard (Repair ship, Buy Ammo/new ships)
Brothel (Increase morale)

**Comment by Break-the-silence** [comment]
oh snap, ok.

further notification sounds depending on what you are doing.

See my comments * :

General Store (buy provisions)
*a cha ching kinda sound...

Tavern (Hire crew, Buy drinks)
*Tavern esque sounds(crowd yammering, with a glass clink)

Consolate (Get contracts)
*Writing on paper sound, like signature wav..

Shipyard (Repair ship, Buy Ammo/new ships)
*Boat bell with hammering metal iron works kinda sound

Brothel (Increase morale)
hmmm hehe, perhaps girl chatter giggles
